sources:
- name: stevenblack
  url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  type: http
  category: Ads&Trackers
  format: txt
  topic_partitions: 3
  topic_replication_factor: 1
- name: malwarefilter
  url: https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-agh.txt
  type: http
  category: Malware
  format: txt
  topic_partitions: 3
  topic_replication_factor: 1
- name: badmojr1hosts
  url: https://badmojr.gitlab.io/1hosts/Lite/adblock.txt
  type: http
  category: Ads&Trackers
  format: txt
  topic_partitions: 3
  topic_replication_factor: 1
- name: adwars
  url: https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
  type: http
  category: Ads&Trackers
  format: txt
  topic_partitions: 3
  topic_replication_factor: 1
- name: testjson
  url: examples/hosts.json
  type: file
  category: Ads&Trackers
  format: json
  topic_partitions: 3
  topic_replication_factor: 1
- name: testcsv
  url: examples/hosts.csv
  type: file
  category: Ads&Trackers
  format: csv
  topic_partitions: 3
  topic_replication_factor: 1
# - name: s3-bucket
#   url: s3://my-bucket/hosts.txt
#   type: s3
#   category: Ads&Trackers
#   format: txt
# - name: hosts-database
#   url: mssql://?:?@?:?/hostsdb
#   type: database
#   category: Ads&Trackers
#   format: db

