services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /app/data/kafka/logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports:
      - "9092:9092"
    volumes:
      - ./data/kafka:/app/data/kafka
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  hosts-topics:
    build:  
      context: .
      dockerfile: topics/Dockerfile
    container_name: hosts-topics
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      PYTHONPATH: /app
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      PROCESS_LOG_DIRS: /app/data/logs
      RETENTION_MS: 600000
    volumes:
      - .:/app

  hosts-producer:
    build: 
      context: .
      dockerfile: producer/Dockerfile
    container_name: hosts-producer
    depends_on:
      hosts-topics:
        condition: service_completed_successfully
    environment:
      PYTHONPATH: /app
      PRODUCER_BATCH_SIZE: 1000
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      PROCESS_LOG_DIRS: /app/data/logs
    volumes:
      - .:/app

  hosts-consumer:
    build:  
      context: .
      dockerfile: consumer/Dockerfile
    container_name: hosts-consumer
    depends_on:
      hosts-topics:
        condition: service_completed_successfully
    environment:
      PYTHONPATH: /app
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_GROUP_ID: hosts-consumer-group
      PROCESS_LOG_DIRS: /app/data/logs
      DELTA_TABLE_PATH: /app/data/delta
      MAX_IDLE_COUNT: 10
      LOADER_BATCH_SIZE: 100000
    volumes:
      - .:/app

  monitor:
    build:
      context: .
      dockerfile: monitoring/Dockerfile
    container_name: monitor
    depends_on:
      - kafka
    environment:
      PYTHONPATH: /app
      PROCESS_LOG_DIRS: /app/data/logs
      MONITOR_SERVICES: hosts-topics:hosts_topics_status.log, hosts-producer:hosts_producer_status.log, hosts-consumer:hosts_consumer_status.log
    volumes:
      - .:/app